#!/usr/bin/env python3
"""Gera s033.json e o md legivel — analogia Chefs e cozinheiros, estetica gouache de receita."""
import json, os

ROLES_PATH = "/home/grec/Projetos/mad-characters/data/roles.json"
OUT_JSON = "/home/grec/Projetos/mad-characters/data/characters/s033.json"
OUT_MD = "/home/grec/Projetos/mad-characters/prompts/individual/s033-chefs-gouache.md"

SHEET_ID = "s033"
SHEET_TITLE = "s033 — Chefs e cozinheiros (Gouache de receita)"

# Prefixo de estetica + enquadramento consistente (busto, waist-up) para os 100.
STYLE = ("Warm gouache recipe-card illustration, waist-up bust portrait of ")
SUFFIX = (", centered single character, consistent framing, uniform chroma-key "
          "green background (#00b140), no text, no logo, high detail")

# (character_name, character_desc_pt, chef_subject_en_with_props)
# chef_subject descreve QUEM é o cozinheiro + adereços que leem o role.
DATA = {
"r001": ("Chef Executivo Aurélio",
    "O chef executivo que desenha o menu inteiro; segura a planta da cozinha e prova cada estação.",
    "a confident executive head chef in a tall starched toque, holding a rolled kitchen blueprint of the whole menu, tasting spoon tucked in pocket, apron with many station badges"),
"r002": ("Sous-Chef Téo",
    "O sous-chef que comanda a linha; prancheta de comandas e concha de autoridade.",
    "a sous-chef line leader in a white double-breasted jacket, holding an order-ticket clipboard in one hand and a ladle in the other, whistle on a lanyard"),
"r003": ("Chef Mestre Estêvão",
    "O cozinheiro de referência da casa; caderno de técnicas gasto e faca de mestre.",
    "a seasoned master chef with graying temples, worn technique notebook under arm, a single revered chef's knife held upright, calm expert expression"),
"r004": ("Grande Chef Prisco",
    "O chef principal, autoridade máxima da brigada; medalha de guia gastronômico e colher cerimonial.",
    "a principal grand chef in an immaculate jacket with a guide-star medal pinned, holding a ceremonial tasting spoon, dignified posture"),
"r005": ("Chef de Cozinha Manô",
    "Gerente da cozinha; escala de turnos na mão e olhar que cuida da brigada.",
    "a kitchen manager chef holding a staff rota schedule board, warm caring expression, keys to the pantry on belt, tidy jacket"),
"r006": ("Chef Menu Paloma",
    "Define o que vai ao menu e por quê; prancheta de menu e lápis de degustação.",
    "a menu-planning chef holding a large menu board with dish sketches, pencil behind ear, tasting the concept thoughtfully"),
"r007": ("Dona do Cardápio Ivete",
    "A voz do prato certo para o cliente; carta de menu priorizada e caneta vermelha.",
    "a menu-owner chef holding a prioritized dish list with red pen marks, deciding the order of courses, decisive smile"),
"r008": ("Coordenadora Neusa",
    "Sincroniza várias cozinhas num banquete; painel de cronograma de serviço e sino.",
    "a program-coordinator chef holding a service timeline board with multiple kitchens marked, small brass service bell, organized stance"),
"r009": ("Chef de Serviço Bento",
    "Toca um banquete do início ao fim; cronograma Gantt de pratos e ampulheta de cozinha.",
    "a project-chef holding a course-timeline chart and a kitchen sand timer, apron pockets full of tickets, focused"),
"r010": ("Facilitador Scrum Quim",
    "Remove obstáculos da linha; quadro de comandas kanban e sineta de rodada.",
    "a scrum-master cook standing by a small ticket kanban board, holding a round-service bell, encouraging gesture, sticky notes on apron"),
"r011": ("Cozinheiro de Base Ravi",
    "O cozinheiro do fundo da casa que faz o caldo-mãe; panela grande e cinta de facas.",
    "a backend prep cook stirring a large stockpot of mother sauce, knife roll on belt, sturdy apron, steam rising"),
"r012": ("Chef de Passagem Aline",
    "Desenha o passe entre cozinha e salão; janela de expedição e comandas encaixadas.",
    "an api-designer expediting chef at a service pass window, arranging labeled ticket rails, plating spoon in hand, clear organized layout"),
"r013": ("Cozinheiro de Estações Dinho",
    "Divide o prato em pequenas estações independentes; várias panelinhas idênticas numa bandeja.",
    "a microservices cook holding a tray of many small identical pots each with its own label, modular mise-en-place, methodical"),
"r014": ("Chef da Linha Pipeline Célia",
    "Monta a linha de produção do prato passo a passo; esteira de mise en place e concha.",
    "a pipeline-line chef beside an assembly line of prep bowls flowing in sequence, ladle in hand, apron with flow-arrow patches"),
"r015": ("Cozinheiro de Insumos Gael",
    "Recebe e prepara toda a matéria-prima; caixotes de ingredientes e balança.",
    "a data-ingredient cook carrying crates of raw produce to a big scale, sorting bins behind, weighing ingredients, robust apron"),
"r016": ("Guardiã da Despensa Zilda",
    "Administra a despensa e o estoque; prateleiras de conservas rotuladas e chave-mestra.",
    "a pantry-database keeper holding a master key before shelves of neatly labeled jars, inventory ledger under arm, careful gaze"),
"r017": ("Cozinheiro de Consultas Íris",
    "Acha o ingrediente exato na despensa num átimo; lupa e ficha de busca de conservas.",
    "a query-specialist cook holding a magnifying glass over a labeled preserve jar, index card of shelf codes, precise expression"),
"r018": ("Cozinheiro do Rechaud Caco",
    "Mantém pratos quentes prontos na hora; rechaud/banho-maria e prato coberto.",
    "a caching cook tending a warming bain-marie of ready plates, holding a domed cloche, quick-serve stance"),
"r019": ("Cozinheiro do Passe Nara",
    "Enfileira comandas na ordem certa; trilho de tickets e campainha de fila.",
    "a message-queue cook managing a long ticket rail in order, ringing a queue bell, tickets clipped in sequence"),
"r020": ("Cozinheira Buscadora Sol",
    "Encontra qualquer receita no arquivão da casa; fichário giratório e lupa.",
    "a search cook spinning a big recipe card index rolodex, magnifier in hand, finding the right card, alert look"),
"r021": ("Chef de Empratamento Bruna",
    "Monta o prato que vai à mesa; pinça de plating e prato acabado bonito.",
    "a frontend plating chef holding fine plating tweezers over a beautifully finished plate, squeeze bottle of sauce, artistic focus"),
"r022": ("Cozinheiro de Guarnição Léo",
    "Cuida dos componentes visíveis do prato; bandeja de guarnições e pincel de brilho.",
    "a ui-garnish cook arranging visible plate components, pastry brush for glaze, tray of neat garnishes, tidy hands"),
"r023": ("Chef de Experiência Dora",
    "Pensa como o cliente sente o prato; storyboard de refeição e colher de prova.",
    "a ux-chef holding a meal-experience storyboard of the dining journey, tasting spoon, empathetic thoughtful expression"),
"r024": ("Chef de Padrões Vítor",
    "Cria o guia de empratamento da casa; molde de emplatamento e cartela de porções.",
    "a design-systems chef holding plating stencils and a portion-swatch card, standard ring molds, consistent tidy layout"),
"r025": ("Cozinheira Inclusiva Fê",
    "Garante prato para todas as restrições; carta de alérgenos em braile e ícones.",
    "an accessibility cook holding an allergen chart with braille and clear icons, adaptive utensils, welcoming inclusive gesture"),
"r026": ("Cozinheiro Expresso Rui",
    "Faz o prato sair rápido sem perder ponto; cronômetro e frigideira leve.",
    "a web-performance cook holding a stopwatch and a light quick saute pan, motion of fast service, lean efficient stance"),
"r027": ("Estilista de Prato Cléo",
    "Cuida do acabamento e do estilo do prato; jogo de espátulas finas e pó decorativo.",
    "a css-styling cook with a set of fine offset spatulas and a shaker of decorative powder, styling a plate edge, elegant touch"),
"r028": ("Cozinheira de Movimento Duda",
    "Faz o prato ganhar vida na mesa; molho flambado e gesto de finalização à la minute.",
    "an animation cook performing a tableside flambe with a small pan of flaming sauce, dramatic finishing gesture, sparks of motion"),
"r029": ("Cozinheiro Ambulante Téo",
    "Cozinha de food truck, cabe no bolso; caixa portátil de mise en place e frigideira compacta.",
    "a mobile food-truck cook holding a compact portable mise-en-place kit and a small pan, on-the-go apron, cheerful"),
"r030": ("Chef da Maçã Ian",
    "Cozinha fina do ecossistema da fruta; avental impecável e faca de precisão polida.",
    "an iOS-apple chef in a sleek minimalist white apron, polishing a precision knife, a pristine apple garnish on the board, refined"),
"r031": ("Cozinheiro Robozinho Dre",
    "Cozinha aberta e versátil; avental verde-robô e espátula multiuso.",
    "an android cook in a green-tinted apron with a friendly robot pin, holding a versatile spatula, open toolkit of gadgets"),
"r032": ("Cozinheira Ponte Nati",
    "Um preparo que serve dois food trucks ao mesmo tempo; frigideira dupla e ponte de servir.",
    "a react-native cook holding a double-sided pan bridging two service windows at once, dual apron ties, efficient smile"),
"r033": ("Cozinheira Vibrante Bel",
    "Prato bonito e fluido em qualquer casa; concha widget e paleta de molhos coloridos.",
    "a flutter cook holding a palette of colorful sauces and a smooth ladle, vibrant plated bowl, fluid graceful pose"),
"r034": ("Cientista do Sabor Cira",
    "Estuda o porquê do sabor; provetas de reduções e caderno de hipóteses de tempero.",
    "a data-scientist cook holding test tubes of sauce reductions, seasoning-hypothesis notebook, curious analytical look, tasting spoon"),
"r035": ("Chef de Fermento Malu",
    "Ensina a massa a crescer sozinha; pote de fermento natural borbulhante e termômetro.",
    "an ML-engineer cook cradling a bubbling sourdough starter jar, dough thermometer in hand, nurturing training gesture"),
"r036": ("Cozinheiro de Escala Rob",
    "Coloca a receita treinada em produção diária; esteira de fôrmas e painel de temperaturas.",
    "an MLOps cook by a conveyor of proofing molds and a temperature dashboard, deploying the recipe at scale, steady hands"),
"r037": ("Pesquisador de Cozinha Nero",
    "Inventa técnicas que ninguém fez; alambique experimental e caderno de descobertas.",
    "an AI-researcher cook at an experimental culinary still, scribbling in a discovery notebook, wild inventive expression"),
"r038": ("Chef Susurro Lia",
    "Sussurra a instrução perfeita para o prato render; cartão de receita afiado e colher de prova.",
    "a prompt-engineer cook holding a carefully worded recipe card and a tasting spoon, whispering the exact instruction, clever smile"),
"r039": ("Cozinheira das Palavras Ju",
    "Traduz o pedido falado do cliente em prato; bloco de comandas e ouvido atento.",
    "an NLP cook holding an order pad, hand cupped to ear translating a spoken request into a dish, attentive expression"),
"r040": ("Cozinheiro do Olho Vic",
    "Reconhece o ponto do prato só de olhar; lupa sobre a grelha e escala de cor de assado.",
    "a computer-vision cook inspecting a grill through a magnifier, holding a roast-color reference chart, keen eye"),
"r041": ("Provador Analista Duca",
    "Analisa e reporta o que o prato revela; ficha de degustação e roda de sabores.",
    "a data-analyst taster holding a tasting scorecard and a flavor wheel, marking notes, focused evaluative look"),
"r042": ("Cozinheira de Painel Bia",
    "Resume o serviço em números; quadro de vendas do dia e giz.",
    "a BI-analyst cook chalking a daily specials sales board with simple charts, apron with chalk dust, presenting proudly"),
"r043": ("Cozinheiro de Métricas Ari",
    "Prepara os dados do serviço para virar painel; fichas organizadas e régua de medida.",
    "an analytics-engineer cook organizing service tally cards into neat stacks with a measuring ruler, tidy data mise-en-place"),
"r044": ("Chef de Apresentação Van",
    "Transforma números em prato visual; travessa em formato de gráfico e molhos coloridos.",
    "a data-viz cook plating a chart-shaped platter with colorful sauce bars, squeeze bottles, artful presentation"),
"r045": ("Cozinheiro de Instalação Dej",
    "Monta e liga toda a cozinha; caixa de ferramentas e botijão de gás conectado.",
    "a devops cook with a tool belt connecting a gas line to the stove, wrench in hand, setting up the whole kitchen, hands-on"),
"r046": ("Guardião do Fogão Sil",
    "Mantém a cozinha sempre de pé; extintor pequeno e checklist de confiabilidade.",
    "an SRE cook holding a small fire extinguisher and a reliability checklist, watching the stoves stay lit, vigilant calm"),
"r047": ("Chef de Plataforma Otto",
    "Constrói a bancada onde todos cozinham; bancada modular e caixa de utensílios comuns.",
    "a platform cook presenting a modular prep station with shared utensil trays, building the base others cook on, proud builder"),
"r048": ("Arquiteta de Nuvem Céu",
    "Projeta a cozinha central que serve muitas filiais; maquete de cozinha em nuvem de vapor.",
    "a cloud-architect cook holding a model of a central kitchen amid rising steam clouds, blueprint of many branch stoves, visionary"),
"r049": ("Timoneiro Kai",
    "Coordena dezenas de panelas como um leme; roda de leme feita de conchas e avental naval.",
    "a kubernetes cook steering a ship's-wheel made of ladles orchestrating dozens of pots, container crates behind, commanding"),
"r050": ("Cozinheiro dos Canos Nel",
    "Cuida do encanamento e do gás da cozinha; chave de cano e mangueira enrolada.",
    "a network cook holding a pipe wrench with a coiled hose over shoulder, connecting kitchen plumbing, practical stance"),
"r051": ("Zelador da Cozinha Val",
    "Mantém tudo funcionando nos bastidores; molho de chaves e prancheta de manutenção.",
    "a sysadmin cook with a big keyring and a maintenance clipboard, tending kitchen equipment, dependable expression"),
"r052": ("Chef de Expedição Rô",
    "Libera o prato para a mesa no ponto certo; carimbo de liberação e bandeja de saída.",
    "a release cook holding an approval stamp over a finished plate on an outgoing tray, checking readiness, sign-off gesture"),
"r053": ("Cozinheiro de Montagem Gus",
    "Junta os componentes no prato final; bandeja de peças de mise e esquema de montagem.",
    "a build cook assembling plate components from a parts tray following an assembly diagram, methodical hands"),
"r054": ("Cozinheira do Passe Contínuo Dê",
    "Faz prato pronto virar servido sem parar; esteira contínua e sino de passe automático.",
    "a CICD cook by a continuous conveyor moving ready plates to the pass with an auto bell, seamless flow, smooth motion"),
"r055": ("Chef de Segurança Alimentar Ester",
    "Blinda a cozinha contra contaminação; termômetro de segurança e luvas e escudo de higiene.",
    "a food-safety chef holding a safety thermometer and wearing protective gloves, a hygiene shield emblem on apron, guarding expression"),
"r056": ("Cozinheiro Testa-Falhas Pug",
    "Tenta furar a segurança da cozinha antes do inspetor; luva preta e swab de teste.",
    "a pentester cook in a black glove holding a contamination test swab, probing for weak spots, sly investigative look"),
"r057": ("Cozinheiro de Blindagem App Zé",
    "Protege cada preparo individual; tampa lacrada e selo de segurança em cada pote.",
    "an appsec cook sealing each prep container with a security lid and tamper seal, careful protective gesture, row of sealed jars"),
"r058": ("Chef dos Segredos Cifra",
    "Guarda a receita secreta em código; livro de receitas cadeado e chave decodificadora.",
    "a cryptographer chef holding a padlocked recipe book and a decoder key, secret-formula card half hidden, enigmatic smile"),
"r059": ("Fiscal da Norma Cida",
    "Garante que a cozinha segue todas as regras; manual de normas e selo de conformidade.",
    "a compliance cook holding a regulations manual and a certification seal stamp, checking the kitchen against rules, upright posture"),
"r060": ("Guardiã da Privacidade Perla",
    "Protege os dados do cliente na comanda; comanda com nome tarjado e cofre de fichas.",
    "a privacy cook holding an order ticket with the name redacted, a small locked ticket box, discreet protective gesture"),
"r061": ("Cozinheiro do Incêndio Brás",
    "Age quando algo pega fogo na linha; extintor grande e capacete de emergência.",
    "an incident-responder cook gripping a large fire extinguisher, small emergency helmet, alert urgent stance, wisp of smoke"),
"r062": ("Cozinheira do Mapa de Riscos Tuê",
    "Antecipa onde a cozinha pode falhar; mapa da cozinha com pontos de perigo marcados.",
    "a threat-modeler cook holding a kitchen floor map with hazard points circled in red, thoughtful anticipatory look, pointer in hand"),
"r063": ("Provadora-Chefe Quitéria",
    "Prova tudo antes de ir à mesa; colher de prova e ficha de aprovação.",
    "a QA head-taster cook holding a tasting spoon and an approval checklist card, evaluating a plate, discerning expression"),
"r064": ("Cozinheiro do Robô-Prova Sam",
    "Automatiza a degustação repetitiva; braço mecânico com colher e bateria de amostras.",
    "an SDET cook beside a small mechanical tasting arm holding a spoon over a row of sample cups, automation gadget, precise"),
"r065": ("Cozinheiro de Carga Léo",
    "Testa a cozinha no auge do movimento; pilha enorme de comandas e cronômetro.",
    "a performance-tester cook holding a huge stack of order tickets and a stopwatch, stress-testing the line, sweaty determined"),
"r066": ("Provador Manual Zeca",
    "Prova prato por prato, com calma; colherzinha e caderninho de anotações.",
    "a manual-tester cook tasting dish by dish with a small spoon and a little notebook, patient careful expression"),
"r067": ("Provadora Inclusiva Meg",
    "Testa se todos conseguem apreciar o prato; carta de alérgenos e utensílio adaptado.",
    "an accessibility-tester cook checking a dish against an allergen card with an adaptive utensil, considerate testing gesture"),
"r068": ("Escrevente de Receitas Clô",
    "Escreve a receita clara para qualquer um repetir; ficha de receita caprichada e pena.",
    "a technical-writer cook penning a tidy recipe card with a quill, neat handwritten steps, organized apron of cards"),
"r069": ("Cozinheira Demonstradora Bela",
    "Mostra a receita ao vivo para a plateia; colher erguida e balcão de demonstração.",
    "a developer-advocate cook holding a spoon up to an audience over a demo counter, enthusiastic teaching gesture, warm smile"),
"r070": ("Estrategista de Menu Cau",
    "Planeja a história que o menu conta; mapa de menu temático e caderno de conceito.",
    "a content-strategist cook holding a thematic menu map and a concept notebook, planning the menu narrative, thoughtful"),
"r071": ("Cozinheira Tradutora Kim",
    "Adapta a receita para cada país; menu em vários idiomas e temperos regionais.",
    "a localization cook holding a multi-language menu and a rack of regional spices, adapting the dish per culture, friendly"),
"r072": ("Designer de Prato Lena",
    "Desenha a experiência completa do prato; esboço do prato e paleta de ingredientes.",
    "a product-designer cook holding a full plate concept sketch and an ingredient color palette, composing the dish, creative focus"),
"r073": ("Cozinheira Visual Fabi",
    "Cuida da beleza final do prato; pincel de molho e paleta de cores comestíveis.",
    "a visual-designer cook with a saucing brush and a palette of edible colors, painting a plate, artistic elegant pose"),
"r074": ("Cozinheiro de Interação Téo",
    "Cria pratos que o cliente monta na mesa; kit de montar taco e gesto convidativo.",
    "an interaction-designer cook presenting a build-your-own taco kit with inviting hands, interactive components, playful"),
"r075": ("Cozinheiro de Movimento Ciça",
    "Faz o prato performar; jato de calda em fio e gesto de finalização fluida.",
    "a motion-designer cook drizzling a flowing ribbon of sauce, dynamic finishing gesture, sense of graceful movement"),
"r076": ("Ilustradora de Pratos Manu",
    "Pinta cenas comestíveis no prato; pincel fino e prato com desenho de calda.",
    "an illustrator cook painting an edible scene on a plate with a fine brush, sauce-drawing in progress, delighted artistic look"),
"r077": ("Cozinheira de Guarnições Ester",
    "Produz os enfeites reutilizáveis do prato; bandeja de guarnições prontas e cortadores.",
    "an asset-designer cook with a tray of ready-made reusable garnishes and shaped cutters, stocking decorative components, tidy"),
"r078": ("Chef de Assinatura Nô",
    "Cria a identidade da casa no prato; selo de calda com o brasão e prato-assinatura.",
    "a brand-designer cook stamping a signature sauce crest onto a plate, holding the house emblem mold, proud identity gesture"),
"r079": ("Cozinheiro do Som Lino",
    "Cuida do estalar e do chiar do prato; frigideira chiante e concha de escuta.",
    "a sound-designer cook holding a sizzling pan to his ear, listening to the crackle, playful attentive expression, steam"),
"r080": ("Escultor de Comida Ravi",
    "Esculpe volumes no prato; faca de escultura e legume entalhado tridimensional.",
    "a 3D-artist cook carving a sculpted vegetable centerpiece with a carving knife, three-dimensional food sculpture, focused craft"),
"r081": ("Chef do Jogo do Menu Gil",
    "Desenha o menu como um jogo de degustação; roleta de pratos e ficha de regras.",
    "a game-designer cook holding a tasting-game spinner and a rules card, designing a playful menu, mischievous grin"),
"r082": ("Chef do Percurso Nina",
    "Desenha o passo a passo do menu degustação; mapa de percurso de pratos e marcadores.",
    "a level-designer cook holding a tasting-menu course map with markers, laying out the meal path, planning gesture"),
"r083": ("Chef Contadora Sol",
    "Conta uma história em cada prato do menu; livro de contos culinário e prato narrativo.",
    "a narrative-designer cook holding an open culinary storybook beside a story-themed plate, gesturing a tale, warm expressive look"),
"r084": ("Cozinheiro do Jogo Dado",
    "Cozinha experiências interativas e divertidas; espátula-controle e prato lúdico.",
    "a game-developer cook holding a controller-shaped spatula over a playful themed plate, energetic fun expression"),
"r085": ("Cozinheiro do Brilho Rai",
    "Cuida do brilho e da textura da superfície; maçarico e prato com espelho de calda.",
    "a graphics-shader cook wielding a kitchen torch glazing a mirror-shiny sauce surface, glossy finish, concentrated"),
"r086": ("Cozinheiro Miniatura Bit",
    "Cozinha em espaço mínimo com precisão; fogareiro minúsculo e pinça fina.",
    "an embedded cook at a tiny single-burner stove with fine tweezers, compact precise mise-en-place, meticulous"),
"r087": ("Cozinheira das Brasas Fê",
    "Domina o controle base do fogo; termômetro de brasa e leque de fogo.",
    "a firmware cook controlling ember heat with a coal thermometer and a firefan, base-fire mastery, steady watchful look"),
"r088": ("Cozinheiro Conectado Neo",
    "Liga sensores por toda a cozinha; termômetros sem fio e painel de leituras.",
    "an IoT cook holding several wireless thermometers linked to a readings panel, sensors across the station, connected gesture"),
"r089": ("Cozinheiro do Livro-Razão Cripto",
    "Registra cada receita num livro imutável e compartilhado; livro-corrente acorrentado e selo.",
    "a blockchain cook holding a chained ledger book of recipes with wax seals, immutable record gesture, serious"),
"r090": ("Auditora de Contratos Vera",
    "Confere se a receita-contrato cumpre o combinado; ficha-contrato e lupa.",
    "a smart-contract-auditor cook examining a contract-recipe card with a magnifier, checking each clause-step, scrutinizing look"),
"r091": ("Chef Imersivo Íris",
    "Cria pratos com realidade aumentada na mesa; óculos AR e prato holográfico de vapor.",
    "an AR-VR cook wearing sleek AR goggles beside a plate with a holographic steam projection, immersive gesture, futuristic"),
"r092": ("Cozinheiro Automatizado Bo",
    "Constrói braços que cozinham sozinhos; braço robótico com concha e chave de robô.",
    "a robotics cook adjusting a small robotic arm holding a ladle, robot wrench in hand, automation of cooking, inventive"),
"r093": ("Cozinheiro do Crescimento Duda",
    "Faz a casa lotar; funil de degustação e placa de fila crescente.",
    "a growth cook holding a tasting funnel and a rising-crowd chart, drawing more diners in, upbeat inviting gesture"),
"r094": ("Cozinheira do Achado Nê",
    "Faz o prato aparecer para quem procura; placa de destaque e ímã de clientes.",
    "an SEO cook holding a spotlight sign over a featured dish and a customer magnet, making the plate discoverable, bright smile"),
"r095": ("Cozinheiro de Vitrine Téo",
    "Divulga os pratos com apelo; carrinho de amostras e cartaz de degustação.",
    "a marketing-tech cook pushing a sample cart with a tasting poster, promoting dishes, persuasive cheerful expression"),
"r096": ("Chef de Soluções Rafa",
    "Adapta o prato ao gosto exato do cliente; menu customizável e caderno de pedidos especiais.",
    "a solutions cook holding a customizable menu and a special-requests notebook, tailoring a dish to the guest, helpful"),
"r097": ("Cozinheiro do Balcão Dão",
    "Resolve o que deu errado no prato do cliente; comanda de troca e prato refeito na hora.",
    "a support cook holding a redo-order ticket and a freshly remade plate, reassuring fix-it gesture, kind attentive look"),
"r098": ("Chef de Salão Vivi",
    "Vende o prato à mesa com convicção; carrinho de degustação e menu aberto.",
    "a sales cook presenting an open menu at a tasting trolley tableside, confident persuasive gesture, warm charismatic smile"),
"r099": ("Cozinheira das Contas Fina",
    "Controla o custo de cada prato; balança de porção e caderno de custos.",
    "a finops cook weighing a portion on a cost scale beside a ledger of dish costs, thrifty measuring gesture, precise"),
"r100": ("Chef Jurídico Bento",
    "Garante que a receita respeita direitos e normas; contrato de fornecedor e selo de aprovação.",
    "a legal-counsel cook holding a supplier contract and an approval seal, reviewing recipe rights, formal careful expression"),
}

def main():
    with open(ROLES_PATH, encoding="utf-8") as f:
        raw = json.load(f)
    roles = raw if isinstance(raw, list) else raw.get("roles", raw)
    roles = sorted(roles, key=lambda r: r["id"])

    objs = []
    md = [f"# {SHEET_TITLE}", "",
          "Analogia: Chefs e cozinheiros. Estetica: gouache de receita (guache quente, "
          "cartao de receita pintado). Enquadramento: busto (waist-up), centralizado, "
          "fundo verde chroma-key uniforme.", ""]

    for r in roles:
        rid = r["id"]
        name, desc, subject = DATA[rid]
        nano = STYLE + subject + SUFFIX
        objs.append({
            "char_id": f"{SHEET_ID}-{rid}",
            "sheet_id": SHEET_ID,
            "role_id": rid,
            "role_slug": r["slug"],
            "role_name": r["name"],
            "character_name": name,
            "character_desc": desc,
            "nano_prompt": nano,
        })
        md.append(f"### {rid} {r['name']} — {name}")
        md.append("")
        md.append(desc)
        md.append("")
        md.append(f"> {nano}")
        md.append("")

    assert len(objs) == 100, f"esperado 100, obtido {len(objs)}"
    with open(OUT_JSON, "w", encoding="utf-8") as f:
        json.dump(objs, f, ensure_ascii=False, indent=2)
    with open(OUT_MD, "w", encoding="utf-8") as f:
        f.write("\n".join(md))
    # valida parse
    with open(OUT_JSON, encoding="utf-8") as f:
        json.load(f)
    print(f"OK {len(objs)} objetos")

if __name__ == "__main__":
    main()
