#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Gera characters/s100.json e prompts individuais para o sheet s100 (Impressionismo / Pincelada Monet)."""
import json, os

SHEET_ID = "s100"
SLUG = "impressionismo"
ROLES_PATH = "/home/grec/Projetos/mad-characters/data/roles.json"
OUT_JSON = f"/home/grec/Projetos/mad-characters/data/characters/{SHEET_ID}.json"
OUT_MD = f"/home/grec/Projetos/mad-characters/prompts/individual/{SHEET_ID}-{SLUG}.md"

STYLE = ("Impressionist oil painting in the loose broken-color brushstrokes of Claude Monet, "
         "luminous dappled sunlight, vibrant plein-air palette, soft feathered edges, visible thick daubs of paint; "
         "a single full-length standing figure of ")
SUFFIX = (", centered single character, consistent framing, uniform chroma-key green background (#00b140), "
          "no text, no logo, high detail")

# role_id -> (character_name, character_desc_pt, props_clause_en)
DATA = {
 "r001": ("Auguste, o Paisagista",
   "Um paisagista de jardim que rascunha a planta de uma ponte e alamedas; dentro do impressionismo ele é o arquiteto — a planta enrolada, o esquadro e o gesto de quem projeta o todo comunicam o papel.",
   "a distinguished belle-epoque garden landscaper unrolling a large architectural plan of a bridge and tree-lined paths, brass set-square and plumb line in hand, one arm sweeping to sketch the whole design in the air, confident visionary expression"),
 "r002": ("Capitão Rémy",
   "O timoneiro-líder de uma equipe de remadores, dando o ritmo com o remo e a bandeirola de largada — o Tech Lead que guia a tripulação.",
   "a rowing-crew captain standing in striped boating attire, holding a long oar in one hand and a small red signal flag in the other, directing an unseen crew, steady commanding gaze"),
 "r003": ("Mestre Théodore",
   "Um jardineiro-mestre veterano com nível de latão e tesoura de poda, autoridade calma que orienta os outros — o Staff Engineer.",
   "a seasoned master gardener in a work smock, holding a large brass spirit level and gleaming pruning shears, calm authoritative bearing, sleaves at his shoulders"),
 "r004": ("Le Vieux Camille",
   "O pintor-mentor mais respeitado do ateliê, palheta na mão e coroa de louros discreta, supervisionando com sabedoria — o Principal Engineer.",
   "a distinguished elderly master painter with white beard, holding a well-used wooden palette and brushes, a subtle laurel wreath, wise mentoring smile, overseeing pose"),
 "r005": ("Anfitrião Léon",
   "O anfitrião cordial do café que organiza o grupo, relógio de bolso e livro de reservas em mãos — o Engineering Manager.",
   "a genial cafe host in waistcoat and apron, pocket watch open in one hand and a guest ledger under his arm, warm organizing smile welcoming a group"),
 "r006": ("Madame Colette",
   "Uma elegante mecenas que seleciona flores no mercado, decidindo o que vale cultivar — a Product Manager que prioriza.",
   "an elegant lady patron in a summer dress and hat, curating a market basket of hand-picked flowers, thoughtfully choosing one bloom, discerning expression"),
 "r007": ("Dona Séraphine",
   "A dona da propriedade com o pergaminho de escritura e um cesto de frutas maduras, orgulhosa do que é seu — a Product Owner.",
   "a proud estate owner in a fine gown holding a rolled property deed and a basket of ripe fruit, protective satisfied posture"),
 "r008": ("Chefe de Estação Gustave",
   "O chefe da estação ferroviária coordenando os trens (motivo Gare Saint-Lazare), relógio e quadro de horários — o Program Manager.",
   "a railway station master in uniform cap, holding a large pocket watch and a schedule board, steam curling around him, coordinating attentive stance"),
 "r009": ("Regente Bertrand",
   "O organizador da regata com cronômetro, bandeira e mapa do percurso — o Project Manager que fecha o cronograma.",
   "a regatta organizer in blazer and straw boater, holding a stopwatch and a course map, a small flag tucked under his arm, focused planning look"),
 "r010": ("Timoneiro Odette",
   "A coxswain que marca a cadência dos remadores com pequeno megafone e macete de ritmo — a Scrum Master.",
   "a rowing coxswain in a light jacket, small brass megaphone in one hand and a rhythm mallet in the other, calling cadence, encouraging expression"),
 "r011": ("Marceneiro Henri",
   "Um construtor de barcos na carcaça de um casco, malho e formão, serragem no ar — o Backend Developer que ergue a estrutura.",
   "a boat builder in rolled sleeves and apron working a wooden hull, wooden mallet and chisel in hand, wood shavings floating, sturdy focused craftsman"),
 "r012": ("Engenheiro Fabien",
   "Apresenta a maquete de uma graciosa passarela de ferro, elo entre as margens — o API Designer.",
   "a bridge engineer presenting a small elegant wrought-iron footbridge model on his palm, offering a connecting handshake, precise proud gesture"),
 "r013": ("Guardião Marcel",
   "O guardião de uma pequena frota de barquinhos amarrados, cuidando de cada um — o Microservices Engineer.",
   "a fleet keeper on a jetty tending many small tethered rowboats, holding several mooring ropes fanned out, attentive multitasking pose"),
 "r014": ("Écluse Basile",
   "O guarda-eclusa que abre os canais e deixa a água correr, manivela da comporta na mão — o Pipeline Developer.",
   "a canal lock-keeper in cap and vest, turning a large iron lock crank, water channels flowing at his feet, steady controlling stance"),
 "r015": ("Moleiro Théo",
   "O moleiro guardião da roda d'água, canalizando sacas de grão pelo moinho — o Data Engineer.",
   "a miller beside a water-wheel, carrying a grain sack over his shoulder and guiding a millstream chute, dusty diligent worker"),
 "r016": ("Sommelier Aurélien",
   "O mestre da adega, lanterna e livro-razão entre barris rotulados — o DBA que guarda e organiza os dados.",
   "a cellar master in a wine cave holding a lantern and a leather ledger, rows of labeled barrels behind, careful custodial expression"),
 "r017": ("Arquivista Lucien",
   "O arquivista que ordena fichas num catálogo, lupa em punho para achar rápido — o SQL Specialist.",
   "an archivist sorting index cards in a wooden card-catalog drawer, magnifying glass in hand, meticulous searching look"),
 "r018": ("Glaçon Émile",
   "O guardião da casa de gelo que estoca blocos para busca instantânea, tenaz e caixa fria — o Caching Engineer.",
   "an icehouse keeper holding large ice tongs gripping a clear ice block, a cold crate at his side, brisk efficient stance"),
 "r019": ("Postier Adrien",
   "O separador dos correios diante dos escaninhos, cartas empilhadas em ordem — o Message Queue Engineer.",
   "a postal sorter at a wall of pigeonholes, an orderly stack of letters in hand, methodically queuing mail, tidy focused pose"),
 "r020": ("Explorador Sylvain",
   "O lampião-escoteiro com luneta e lanterna, procurando o que se busca — o Search Engineer.",
   "a lamplighter-scout with a brass spyglass raised to one eye and a lantern in the other hand, searching the distance, keen expression"),
 "r021": ("Vitrinista Margot",
   "A decoradora de vitrine que arruma uma bela montra com fita e pincel — o Frontend Developer.",
   "a shop-window dresser arranging a pretty storefront display, holding a ribbon and a fine brush, tasteful arranging gesture, cheerful"),
 "r022": ("Décorateur Pascal",
   "O decorador de interiores pendurando painéis emoldurados, nível e amostras de cor — o UI Engineer.",
   "an interior decorator hanging framed decorative panels, a small level and color swatches in hand, precise tasteful pose"),
 "r023": ("Passeur Amélie",
   "A projetista de caminhos de jardim que assenta pedras para um passeio fácil, mapa de trilha na mão — a UX Designer.",
   "a garden-path designer laying flat stepping stones for an easy stroll, holding a small walking map, gently guiding gesture, considerate look"),
 "r024": ("Azulejista Corentin",
   "O criador de padrões que carrega uma bandeja de azulejos combinantes e estênceis — o Design Systems Engineer.",
   "a tile-pattern maker holding a tray of matching hand-painted tiles and stencils, arranging a repeating motif, systematic tidy pose"),
 "r025": ("Ouvreuse Rosalie",
   "A gentil recepcionista que oferece uma rampa e bengala-guia a um convidado, acolhedora — a Accessibility Specialist.",
   "a kindly usher setting down a small ramp and offering a guiding cane, welcoming an unseen guest with an inclusive open gesture, warm smile"),
 "r026": ("Coursier Félix",
   "O ágil mensageiro de velocípede afinado para velocidade, cronômetro no pescoço — o Web Performance Engineer.",
   "a swift bicycle courier beside an early velocipede, cap and tight jacket, stopwatch on a cord, poised to dash, energetic expression"),
 "r027": ("Alfaiate Justine",
   "A alfaiate de moda drapeando tecido com alfinetes e fita métrica, estilizando a forma — a CSS Specialist.",
   "a fashion tailor draping flowing fabric on a form, pins in her cuff and a measuring tape around her neck, styling gesture, chic focus"),
 "r028": ("Marionnettiste Gaspard",
   "O titeriteiro que gira um zootrópio dando vida ao movimento — o Animation Engineer.",
   "a puppeteer spinning a small zoetrope drum with painted frames, marionette strings in the other hand, delighted animating gesture"),
 "r029": ("Ombrelier Delphine",
   "A fabricante de sombrinhas com uma sombrinha dobrável compacta, portátil e leve — a Mobile Developer.",
   "a parasol maker holding a neat folding parasol half-open, several compact parasols at her side, portable elegant pose"),
 "r030": ("Gantier Léonard",
   "O luveiro refinado exibindo uma luva de botões de pérola, polida e exclusiva — o iOS Developer.",
   "an elegant glovemaker presenting a single polished pearl-buttoned kid glove on a stand, refined precise gesture, poised bearing"),
 "r031": ("Automate Vincent",
   "O funileiro de engenhocas com um pequeno autômato mecânico verde na mão — o Android Developer.",
   "a clockwork tinkerer holding a small green mechanical automaton figure, tiny wrench in the other hand, inventive playful look"),
 "r032": ("Réversible Manon",
   "A alfaiate de casacos reversíveis mostrando uma peça que serve dos dois lados — o React Native Developer.",
   "a tailor showing off a reversible coat flipped to reveal two different linings, holding it open with both hands, clever proud smile"),
 "r033": ("Éventail Clarisse",
   "A leque-maker que agita um leque dobrável pintado, delicado e fluido — o Flutter Developer.",
   "a fan maker fluttering an open painted folding fan, a few closed fans tucked at her waist, graceful airy motion"),
 "r034": ("Naturalista Théophile",
   "O naturalista com rede de borboletas e frascos de espécimes, examinando padrões — o Data Scientist.",
   "a naturalist with a butterfly net over his shoulder, holding a glass specimen jar up with a magnifier, curiously examining patterns, studious look"),
 "r035": ("Colombophile Isaure",
   "A treinadora de pombos-correio ensinando as aves, apito e gaiola — a ML Engineer.",
   "a pigeon trainer with a homing pigeon on her wrist, a training whistle and a small cage, patient teaching gesture, gentle focus"),
 "r036": ("Serrista Norbert",
   "O guardião da estufa que mantém fileiras de mudas, regador e termômetro — o MLOps Engineer.",
   "a greenhouse keeper among rows of potted seedlings, watering can in one hand and a thermometer in the other, tending maintenance pose"),
 "r037": ("Astrônomo Ludovic",
   "O astrônomo com luneta e carta celeste, olhos no alto em busca do desconhecido — o AI Researcher.",
   "an astronomer with a brass telescope on a tripod and a rolled star chart, gazing upward in wonder, contemplative discovering expression"),
 "r038": ("Orateur Baptiste",
   "O poeta-orador eloquente com pena e pergaminho, gesticulando para persuadir — o Prompt Engineer.",
   "an eloquent poet-orator holding a quill and an unrolled scroll, one hand raised in a persuasive rhetorical gesture, expressive articulate look"),
 "r039": ("Truchement Rosine",
   "A tradutora poliglota com dicionários e uma trombeta de fala, ligando línguas — a NLP Engineer.",
   "a polyglot translator holding two thick dictionaries and a small speaking trumpet, mid-interpretation gesture, attentive multilingual air"),
 "r040": ("Silhouettiste Marius",
   "O retratista com câmara obscura e caderno de esboços, lendo um rosto — o Computer Vision Engineer.",
   "a portrait sketcher holding a small camera-obscura box and a sketchpad, studying an unseen face, perceptive observing gaze"),
 "r041": ("Comptable Adèle",
   "A guarda-livros do mercado que soma no ábaco entre livros-razão — a Data Analyst.",
   "a market accountant seated-forward pose holding an abacus and an open ledger, tallying figures, sharp precise concentration"),
 "r042": ("Graphiste Edmond",
   "O desenhista de gráficos ao cavalete apresentando um diagrama de barras à mão — o BI Analyst.",
   "a chart-maker at an easel presenting a hand-drawn bar chart on paper, pointer stick in hand, explanatory confident gesture"),
 "r043": ("Géomètre Solange",
   "A agrimensora com teodolito medindo a terra, precisa e metódica — a Analytics Engineer.",
   "a land surveyor behind a brass theodolite on a tripod, holding a measuring chain, sighting a measurement, methodical precise stance"),
 "r044": ("Cartographe Anatole",
   "O cartógrafo que pinta um mapa ilustrado e decorativo, dado vira imagem — o Data Viz Specialist.",
   "a cartographer painting a decorative illustrated map on a board, fine brush and compass in hand, artistic proud presenting pose"),
 "r045": ("Charpentier Roland",
   "O carpinteiro faz-tudo com cinto de ferramentas erguendo um andaime — o DevOps Engineer.",
   "a handy carpenter with a full leather tool-belt raising a wooden scaffold, hammer in hand, capable building stance, rolled sleeves"),
 "r046": ("Veilleur Damien",
   "O vigia noturno-bombeiro com lanterna e balde de incêndio, sempre alerta — o Site Reliability Engineer.",
   "a night watchman with a raised lantern and a fire bucket, vigilant alert posture scanning for trouble, steady dependable look"),
 "r047": ("Maçon Gérard",
   "O pedreiro de fundações assentando blocos de pedra para a plataforma, colher de pedreiro — o Platform Engineer.",
   "a foundation mason laying large stone platform blocks with a trowel and mortar, level line at hand, solid grounded stance"),
 "r048": ("Aéronaute Célestin",
   "O balonista que sobe na cesta de vime rumo ao céu — o Cloud Architect.",
   "a hot-air balloonist stepping from a wicker basket gondola, holding mooring ropes with a striped balloon rising above, visionary skyward gaze"),
 "r049": ("Batelier Ferdinand",
   "O barqueiro-timoneiro que conduz muitas barcaças enfileiradas com o leme — o Kubernetes Admin.",
   "a helmsman-ferryman steering with a long tiller, guiding a line of small linked barges behind him, orchestrating calm command"),
 "r050": ("Télégraphiste Aline",
   "A linheira do telégrafo estendendo fios entre postes, conectando pontos — a Network Engineer.",
   "a telegraph linewoman stringing wire between poles, a coil of cable over her shoulder and pliers in hand, connecting practical pose"),
 "r051": ("Concierge Barnabé",
   "O zelador da propriedade com um molho enorme de chaves e almotolia — o Systems Administrator.",
   "an estate caretaker holding a big ring of iron keys and an oil can, keeping things running, unflappable dependable expression"),
 "r052": ("Crieur Léopold",
   "O arauto que anuncia o lançamento com sino de mão, voz para todos — o Release Engineer.",
   "a town crier ringing a hand bell, other arm raised announcing, tricorne-like cap, proclaiming a release with a bold open-mouthed call"),
 "r053": ("Briquetier Firmin",
   "O mestre do forno que ergue uma parede tijolo a tijolo, montando o todo — o Build Engineer.",
   "a brick kiln master assembling a wall brick by brick, trowel and a stack of bricks in his arms, steady constructive stance"),
 "r054": ("Meunier Aristide",
   "O operador de esteira do moinho, manivela girando pães em fila de montagem — o CI/CD Engineer.",
   "a mill conveyor operator turning a hand-crank belt carrying a row of loaves in sequence, continuous automated motion, efficient look"),
 "r055": ("Gardien Ambroise",
   "O guardião do portão do castelo com chave grande e escudo, inspecionando quem entra — o Security Engineer.",
   "a castle gatekeeper holding a large iron key and a round shield, inspecting an entrance, watchful protective stance, stern fair expression"),
 "r056": ("Furet Léandre",
   "O gatuno mascarado que testa uma fechadura com gazuas, provando as defesas — o Penetration Tester.",
   "a playful masked cat-burglar in dark cap testing a padlock with lock picks, mischievous testing grin, crouched probing pose"),
 "r057": ("Serrurier Éloi",
   "O chaveiro que instala uma fechadura robusta na porta, blindando o acesso — o AppSec Engineer.",
   "a locksmith fitting a sturdy lock onto a door, ring of picks and a strong padlock in hand, careful securing gesture"),
 "r058": ("Chiffreur Hippolyte",
   "O escrivão de cifras com bastão-cítala e carta lacrada, guardando segredos — o Cryptographer.",
   "a cipher clerk holding a wooden scytale cipher rod and a wax-sealed letter, decoding gesture, secretive clever expression"),
 "r059": ("Notário Prosper",
   "O notário-magistrado com carimbo, selo e livro de regras, verificando conformidade — o Compliance Officer.",
   "a notary in a formal coat holding an official stamp and wax seal over a rulebook, verifying compliance, exacting solemn look"),
 "r060": ("Valet Séverin",
   "O valete discreto que fecha a cortina protegendo a privacidade, envelope lacrado — o Privacy Engineer.",
   "a discreet valet drawing a heavy curtain closed with one hand, holding a sealed envelope in the other, protective private gesture"),
 "r061": ("Pompier Casimir",
   "O capitão da brigada de incêndio com capacete e mangueira, urgência de resposta — o Incident Responder.",
   "a fire-brigade captain in a gleaming helmet gripping a water hose, urgent action stance rushing to a blaze, resolute expression"),
 "r062": ("Stratège Ghislain",
   "O estrategista de xadrez sobre o tabuleiro, antecipando o ataque com a luneta — o Threat Modeler.",
   "a chess strategist leaning over a board with pieces, a small spyglass in hand, anticipating an opponent's move, shrewd calculating look"),
 "r063": ("Inspetora Blanche",
   "A inspetora de qualidade que examina frutas com lupa e descarta a podre — a QA Engineer.",
   "a quality inspector examining an apple with a magnifier over a crate of fruit, setting aside a bad one, discerning scrutinizing expression"),
 "r064": ("Automaticien Régis",
   "O testador-autômato operando uma engenhoca mecânica de ensaios com alavanca — o SDET.",
   "an automation tester operating a mechanical testing contraption, pulling a lever that repeats a check, methodical inventive pose"),
 "r065": ("Chrono Valentine",
   "A treinadora de cronômetro medindo o corredor sob pressão, apito na mão — o Performance Tester.",
   "a stopwatch trainer timing a sprinting runner, whistle to her lips and stopwatch raised, measuring performance, intense focus"),
 "r066": ("Relectrice Josephine",
   "A revisora cuidadosa que confere cada item à mão com sua lista — o Manual Tester.",
   "a careful proofreader checking items one by one against a handwritten checklist, quill ticking a box, patient thorough expression"),
 "r067": ("Éprouveuse Mathilde",
   "A avaliadora que testa rampa e corrimão de olhos vendados e bengala, empática — o Accessibility Tester.",
   "an accessibility tester trying a ramp and handrail while blindfolded, feeling ahead with a white cane, empathetic testing pose"),
 "r068": ("Escriba Fulbert",
   "O escriba-calígrafo à escrivaninha com pena e manuscrito, documentando tudo — o Technical Writer.",
   "a scribe-calligrapher standing at a slanted writing desk, quill in hand over an illuminated manuscript, diligent documenting focus"),
 "r069": ("Bonimenteur Octave",
   "O palestrante carismático de rua que fala à multidão com um livro aberto — o Developer Advocate.",
   "a charismatic street lecturer on a small crate addressing a crowd, open book in one hand and the other flung wide, engaging enthusiastic gesture"),
 "r070": ("Rédacteur Clément",
   "O editor de jornal que compõe a diagramação da folha com cola e tesoura — o Content Strategist.",
   "a newspaper editor arranging a broadsheet layout on a board, paste brush and shears in hand, planning column structure, decisive look"),
 "r071": ("Poteau Béatrice",
   "A pintora de placas multilíngues com bandeiras de nações e um manual de frases — o Localization Engineer.",
   "a multilingual signpost painter beside a post with arrows in several languages, small national flags and a phrasebook in hand, careful adapting pose"),
 "r072": ("Potier Anselme",
   "O oleiro que modela um vaso no torno e ergue a peça acabada, produto elegante — o Product Designer.",
   "a potter shaping a vase at a spinning wheel, presenting a finished elegant vessel in his hands, muddy apron, satisfied crafting expression"),
 "r073": ("Peintre Océane",
   "A pintora ao cavalete com palheta e pincel em riste, arquétipo do artista — o Visual Designer.",
   "a painter at an easel with a loaded palette and a poised brush, stepping back to judge the canvas, absorbed artistic gaze, paint-flecked smock"),
 "r074": ("Pantin Gaultier",
   "O fabricante de brinquedos mecânicos com um pula-pula de cordinha interativo — o Interaction Designer.",
   "a mechanical-toy maker holding a pull-string jumping-jack puppet, demonstrating its motion, playful engaging gesture"),
 "r075": ("Chorégraphe Ninon",
   "A coreógrafa de balé posando a bailarina com gesto amplo e gracioso — o Motion Designer.",
   "a ballet choreographer guiding a dancer's pose with a sweeping graceful gesture, ribboned slippers at her feet, fluid elegant motion"),
 "r076": ("Illustrateur Sidoine",
   "O ilustrador de pena e tinta segurando uma grande prancha ilustrada — o Illustrator.",
   "a pen-and-ink illustrator holding up a large finished illustrated plate, dip pen in the other hand, proud detailed presenting pose"),
 "r077": ("Accessoiriste Firminie",
   "A cenógrafa de adereços com um carrinho de props pintados de palco — o Asset Designer.",
   "a stage prop-maker beside a small cart loaded with colorful painted stage props, holding one prop up, resourceful arranging gesture"),
 "r078": ("Enseigniste Godefroy",
   "O pintor de emblemas que segura um brasão-letreiro de loja pintado à mão — o Brand Designer.",
   "a heraldic sign painter holding a hand-painted shop emblem crest, brush and gold paint in hand, presenting a bold identity, confident look"),
 "r079": ("Musicien Alphonse",
   "O músico de rua com realejo/sanfona, atento ao som e à atmosfera — o Sound Designer.",
   "a street musician playing a hand-cranked hurdy-gurdy, head tilted listening to the tone, expressive musical absorption"),
 "r080": ("Sculpteur Ombeline",
   "A escultora de mármore com cinzel e uma estatueta, empoeirada de trabalho — o 3D Artist.",
   "a marble sculptor with mallet and chisel beside a small statuette, marble dust on her apron, shaping form with focused craft"),
 "r081": ("Maître Fortuné",
   "O mestre de jogos com bolas de pétanque e livro de regras, lúdico e justo — o Game Designer.",
   "a game-master holding a set of petanque boules and a rulebook, inviting a game with a playful gesture, cheerful clever expression"),
 "r082": ("Labyrinthe Perrine",
   "A jardineira do labirinto de sebes projetando o traçado com sua planta — o Level Designer.",
   "a hedge-maze gardener holding a maze plan and pruning shears, gesturing toward a labyrinth layout, inventive planning pose"),
 "r083": ("Conteur Melchior",
   "O bardo contador de histórias com livro ilustrado aberto sob a lanterna — o Narrative Designer.",
   "a storytelling bard holding an open illustrated storybook, a lantern casting warm light, mid-tale captivating gesture, expressive eyes"),
 "r084": ("Forain Urbain",
   "O montador de carrossel ajustando um cavalinho do carrossel, chave em mão — o Game Developer.",
   "a carousel builder fitting a painted merry-go-round horse, wrench in hand, playful assembling stance among bright fairground parts"),
 "r085": ("Verrier Lumière",
   "O artesão de vitral erguendo um painel de vidro luminoso à luz — o Graphics/Shader Engineer.",
   "a stained-glass artisan holding a luminous colored glass panel up to the light, lead came and cutter in hand, glowing awe expression"),
 "r086": ("Horloger Isidore",
   "O relojoeiro com lupa montando engrenagens minúsculas num pequeno estojo — o Embedded Engineer.",
   "a watchmaker with a loupe in his eye assembling tiny gears with fine tweezers over a small watch case, intent precise micro-focus"),
 "r087": ("Boîte-à-musique Reine",
   "A fabricante de caixinha de música cravando o cilindro rotativo que a faz tocar — o Firmware Engineer.",
   "a music-box maker pinning the rotating brass cylinder of a music box, tiny hammer and pins in hand, delicate embedding focus"),
 "r088": ("Girouette Nestor",
   "O fabricante de instrumentos com barômetro e sensores conectados no jardim — o IoT Engineer.",
   "a weather-instrument maker holding a barometer, a weathervane and small connected garden sensors on a wire, tinkering connective pose"),
 "r089": ("Chaînier Onésime",
   "O forjador que forja elos metálicos entrelaçados e guarda um livro de registros — o Blockchain Developer.",
   "a chain-maker forging interlocking metal links at a small anvil, an immutable ledger book at his side, steady forging stance"),
 "r090": ("Vérificateur Placide",
   "O notário que examina com lupa o selo de um contrato acorrentado — o Smart Contract Auditor.",
   "a notary examining a chain-linked contract seal with a magnifier, quill ready to certify, scrutinizing rigorous expression"),
 "r091": ("Stéréoscope Aurore",
   "A observadora que ergue um estereoscópio aos olhos, maravilhada com a ilusão — o AR/VR Engineer.",
   "a viewer holding a wooden stereoscope up to her eyes, a stereo card in hand, wonderstruck immersive expression, leaning into the illusion"),
 "r092": ("Mécanicien Timothée",
   "O construtor de autômatos ao lado de uma figura mecânica de latão — o Robotics Engineer.",
   "an automaton-maker standing beside a life-size brass mechanical figure, wrench and oil can in hand, proud tinkering gesture"),
 "r093": ("Semeur Florent",
   "O semeador que espalha sementes com uma trepadeira crescendo veloz — o Growth Engineer.",
   "a seed-sower scattering seed from a shoulder pouch, a fast-climbing vine spiraling up beside him, optimistic expansive gesture"),
 "r094": ("Panneau Victorine",
   "A que planta um letreiro proeminente na encruzilhada, indicando o caminho — o SEO Specialist.",
   "a signpost placer positioning a prominent directional signpost at a crossroads, angling it for visibility, strategic pointing gesture"),
 "r095": ("Afficheur Gustin",
   "O colador de cartazes com um pôster Belle Époque de propaganda e brocha de cola — o Marketing Technologist.",
   "a bill-poster pasting a colorful belle-epoque advertising poster on a board, paste brush in hand, promotional flourish, lively expression"),
 "r096": ("Commis Séraphin",
   "O prestativo caixeiro que demonstra um aparelho ao cliente, gesticulando a solução — o Solutions Engineer.",
   "a helpful shop clerk demonstrating a small device to an unseen customer, presenting it in open palms, attentive helpful gesture"),
 "r097": ("Concierge Philomène",
   "A concierge simpática no balcão de atendimento com sineta de serviço, atenta — o Support Engineer.",
   "a friendly concierge at a service desk, one hand tapping a small brass service bell, attentive welcoming smile, ready-to-help lean"),
 "r098": ("Marchand Théobald",
   "O charmoso vendedor de mercado apresentando as mercadorias com gesto persuasivo — o Sales Engineer.",
   "a charming market vendor presenting wares from a display tray with a persuasive sweeping gesture, warm convincing smile"),
 "r099": ("Changeur Eustache",
   "O banqueiro-cambista à mesa com balança de moedas e livro-razão, pesando o valor — o FinOps Analyst.",
   "a money-changer at a table with a coin balance scale and a ledger, weighing gold coins, careful cost-conscious expression"),
 "r100": ("Avocat Isambart",
   "O advogado togado com código de leis e balança da justiça, ponderando o direito — o Legal Counsel.",
   "a robed advocate holding a heavy law book and small balance scales of justice, weighing a judgment, dignified measured expression"),
}

with open(ROLES_PATH, encoding="utf-8") as f:
    raw = json.load(f)
roles = raw if isinstance(raw, list) else raw.get("roles", raw)

records = []
for r in roles:
    rid = r["id"]
    name, desc, props = DATA[rid]
    nano = STYLE + props + SUFFIX
    records.append({
        "char_id": f"{SHEET_ID}-{rid}",
        "sheet_id": SHEET_ID,
        "role_id": rid,
        "role_slug": r["slug"],
        "role_name": r["name"],
        "character_name": name,
        "character_desc": desc,
        "nano_prompt": nano,
    })

assert len(records) == 100, f"esperado 100, obtido {len(records)}"

with open(OUT_JSON, "w", encoding="utf-8") as f:
    json.dump(records, f, ensure_ascii=False, indent=2)

# valida parse
with open(OUT_JSON, encoding="utf-8") as f:
    assert len(json.load(f)) == 100

lines = []
lines.append("# s100 — Impressionismo (estética: Pincelada Monet · vibe: luz e cor)\n")
lines.append("Cada role vira uma figura do mundo impressionista (Belle Époque), lida por adereços/pose, "
             "pintada em pincelada Monet. Enquadramento uniforme: figura inteira, fundo verde chroma-key.\n")
for rec in records:
    rid = rec["role_id"]
    lines.append(f"### {rid} {rec['role_name']} — {rec['character_name']}\n")
    lines.append(rec["character_desc"] + "\n")
    lines.append("> " + rec["nano_prompt"] + "\n")

with open(OUT_MD, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))

print("s100: escrito", OUT_JSON, "e", OUT_MD, "com", len(records), "registros")
